version: '3.3'

services:
  dbPostgres:
    image: postgres:15.3-alpine3.18
    container_name: contenedor_db_postgres
    environment:
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=parqueo
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/scripts:/docker-entrypoint-initdb.d
    network_mode: host

  pgAdmin:
    image: dpage/pgadmin4:7.6
    container_name: contenedor_pgAdmin
    depends_on:
      - dbPostgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@email.com
      - PGADMIN_DEFAULT_PASSWORD=abc123
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050

volumes:
  postgres_data: